### PR TITLE
Add Message Passing and Node Classification notes

### PR DESCRIPTION
**Pull request by benjaminangulo**
Thanks for making a contribution to the CS224W course notes! The staff and future students appreciate it. Make sure you've published your changes as a live preview. The URL will look like `https://<your github id>.github.io/cs224w-notes/`. Provide the link to the live preview in your pull request. Also please make sure there are no content, spelling, or grammar mistakes in your pull request before submitting it for review. Strive to make your notes as complete, correct, and as easy to understand as possible. Pull requests that have mistakes, and require many rounds of review before acceptance, will likely receive less extra credit.

Please delete this template and replace it with your own pull request message.

### CODE REVIEW

**Comment by benhannel** [comment]
Please read the pull request template and actually follow those instructions.

**Comment by benjaminangulo** [comment]
Hi Ben!
I actually resolved the issue with the preview, the link should work now. The problem was that I had not selected a theme under the settings section. I'm so sorry for the issues, as I mentioned, this was my first time publishing a website. 
Thanks for your patience.

**Comment by benhannel** [comment]
It looks pretty good overall, but I see a few issues:
- `Y~i~`
- `P(Y~i~= c) = \frac{1}{\vert N_i\vert}{\sum_{(i,j)\in E} W_{(i,j)}} \sum W_{(i,j)} P(Y_j = c)`
- `N~i~`
- The bullets under "Bootstrap phase:" seem to be at the wrong indentation level
- "answersconditional"
- "neighbor variable" => "neighbor variables"
- "are task" => "our task"
- "not guaranteed, this" => "not guaranteed. This"

**Comment by benjaminangulo** [comment]
Hi Ben, I have made the requested edits to the notes. Thank you for your help!

**Comment by benhannel** [comment]
Looks good

**Pull request merged**
