### PR TITLE
PageRank notes

### PR DESCRIPTION
**Pull request by yhr91**
Please let me know if any changes need to be made

### CODE REVIEW

**Comment by benhannel** [comment]
Please deploy your branch via Jeykll so we can view it at https://yhr91.github.io/cs224w-notes/machine-learning-with-networks/

**Comment by yhr91** [comment]
Would it be possible for you to clone this branch and host it locally. I'm not sure if I can deploy it on yhr91.github.io because it's being used to serve a different website

**Comment by benhannel** [comment]
You can create a preview at a subpath or via a different github account

**Comment by yhr91** [comment]
Sorry, I don't understand what either of those options mean

**Comment by yhr91** [comment]
http://www.yusufroohani.com/cs224w-notes/network-methods/pagerank

**Comment by benhannel** [comment]
Thanks for publishing the preview. That's really helpful. The notes look really good overall! A few comments.
- "importance of any node" => "importance of every node"
- In the sum over i -> j, you might want to be more explicit in your notation
- eigen vector => eigenvector, and likewise of eigenvalue
- In the random walk formulation, we only reach the pagerank vector when t approaches infinity. You may want to say this more explicitly.

Overall I really like these notes! Clear and engaging. Just fix the minor issues and I'll merge it.

**Comment by yhr91** [comment]
Thanks for the feedback! I've made the edits you requested, but if I've missed anything please let me know.

**Comment by benhannel** [comment]
Looks like you've got merge conflicts

**Comment by yhr91** [comment]
resolved

**Comment by benhannel** [comment]
Looks good!

**Comment by yhr91** [comment]
Thanks. You'll need to update index.md manually to link to the PageRank page. That was the cause of the merge conflict

**Comment by benhannel** [comment]
Fixed it. Thanks for the heads up.

**Pull request merged**
