### PR TITLE
gnn

### PR DESCRIPTION
**Pull request by zhouxos**

### CODE REVIEW

**Comment by zhouxos** [comment]
A PR from Xiaoqin Zhou

**Comment by benhannel** [comment]
Please deploy your branch via Jeykll so we can view it at https://zhouxdd.github.io/cs224w-notes/machine-learning-with-networks/

**Comment by zhouxos** [comment]
done: https://zhouxdd.github.io/cs224w-notes/machine-learning-with-networks/graph-neural-networks

**Comment by zhouxos** [comment]
not sure how to deploy with Jeykll, but I did get it to display the page

**Comment by benhannel** [comment]
- using deep encoder should be using deep encoders
- "for a new node arrives" => "when a new mouse arrives"

I only went through the first half. Please read through the whole notes again with a fine tooth comb, and strive for correctness, clarity, conciseness, and consistency.

**Comment by zhouxos** [comment]
will update the PR in a little bit

**Pull request closed without merging**
