### PR TITLE
Node Representation Learning

### PR DESCRIPTION
**Pull request by tianyuanhuang**
Add notes of Node Representation Learning in Machine Learning with Networks part.

### CODE REVIEW

**Comment by benhannel** [comment]
Please publish your fork with Jeykll so we can preview your changes at https://tianyuanhuang.github.io/cs224w-notes/

**Comment by tianyuanhuang** [comment]
got it! It should work now.

**Comment by benhannel** [comment]
Thanks for the contribution! Looks good overall. I think there's a minor grammar error in bullet 2 of "Embedding Nodes", but they're solid notes.

**Comment by tianyuanhuang** [comment]
Thanks Ben!

**Pull request merged**
