### PR TITLE
Notes for GNN

### PR DESCRIPTION
**Pull request by zhouxos**
updated notes from Xiaoqin Zhou
Thanks for reviewing!

### CODE REVIEW

**Comment by zhouxos** [comment]
https://zhouxdd.github.io/cs224w-notes/machine-learning-with-networks/graph-neural-networks

**Comment by benhannel** [comment]
- grammar mistake: "The computation graph for all the nodes in the graph with two layers deep will look like the following:"

**Comment by benhannel** [comment]
- "all the parameters are share crossed all nodes"

**Comment by benhannel** [comment]
- Typo? $$e_{vu} = a(W_kh_u^{k-1}, W_kh)v^{k-1}$$

**Comment by zhouxos** [comment]
resolved all comments

**Comment by benhannel** [comment]
"shared crossed all nodes" still isn't fixed. It should be "shared across all nodes"

**Comment by zhouxos** [comment]
thanks for your feedback, updated

**Comment by benhannel** [comment]
Grammar mistake: "explored a simple neighbourhood aggregation methods"

Please value my time more. If you keep submitting notes with basic errors I will stop reading them.

**Pull request closed without merging**
