### PR TITLE
Notes for Generative models for Graph Generation

### PR DESCRIPTION
**Pull request by rc19**
Notes for Generative models for Graph Generation. The site is published at rc19.github.io/cs224w-notes/

### CODE REVIEW

**Comment by mananshah99** [comment]
Can you publish your fork with Jekyll so we can view the notes changes at https://rc19.github.io/cs224w-notes/? Thanks for your contributions!

**Comment by rc19** [comment]
@mananshah99  Done

**Comment by benhannel** [comment]
Feedback:
- "leanred" => "learned"
- "graphmodel" => "graph model"
- This sentence is confusingly worded: "For instance, sampling from the graphmodel can lead to the discovery of new configurations that share same global properties as is, for example, required in drug discovery."
- "Language modeling" => "language modeling"
- Be consistent with latex. All n!, O(n!), etc, should be wrapped in $$ $$
- "sequence of order"?

I only went through the first half. Please read through the whole notes again with a fine tooth comb, and strive for correctness, clarity, conciseness, and consistency (hehe alliteration not intended).

**Comment by benhannel** [comment]
We'll also need you real name in order to assign extra credit, if applicable.

**Comment by rc19** [comment]
Closing it. Will open a new one with the said changes.

**Pull request closed without merging**
